# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/dual/cs5180411/Desktop/Assignment 4 using assign3 real/project_46/project_46.cache/wt} [current_project]
set_property parent.project_path {/home/dual/cs5180411/Desktop/Assignment 4 using assign3 real/project_46/project_46.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {/home/dual/cs5180411/Desktop/Assignment 4 using assign3 real/project_46/project_46.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {/home/dual/cs5180411/Desktop/Assignment 4 using assign3 real/project_46/project_46.srcs/sources_1/imports/Desktop/symbol3.vhf}
  {/home/dual/cs5180411/Desktop/Assignment 4 using assign3 real/project_46/project_46.srcs/sources_1/imports/Desktop/assign4.vhf}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/dual/cs5180411/Desktop/Assignment 4 using assign3 real/project_46/project_46.srcs/constrs_1/imports/Desktop/Basysassign4.xdc}}
set_property used_in_implementation false [get_files {{/home/dual/cs5180411/Desktop/Assignment 4 using assign3 real/project_46/project_46.srcs/constrs_1/imports/Desktop/Basysassign4.xdc}}]


synth_design -top assign4 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef assign4.dcp

catch { report_utilization -file assign4_utilization_synth.rpt -pb assign4_utilization_synth.pb }
